version: '3'
services:
  db:
    image: "postgres:9-alpine"
    container_name: "test-db"
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - my_dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASWORD: 'password'
      POSTGRES_DB: 'test'

  work-test:
    image: job/test:latest
    container_name: test-server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /data/springboot-docker-compose-app
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - db


volumes:
  my_dbdata:
