spring:
  jackson:
    serialization:
      write_enums_using_to_string: true
    deserialization:
      read_enums_using_to_string: true


  jpa:
    hibernate:
      format_sql: true
    generate-ddl: false
    show-sql: false

    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  datasource:
    platform: postgres
    url: jdbc:postgresql://${HOST_DB}:5432/test?createDatabaseIfNotExist=true
    username: admin
    password: password

  hikari:
    leakDetectionThreshold: 10000
    #      idleTimeout: 30000
    #      connectionTimeout: 30000

graphql:
  servlet:
    mapping: /api